- hosts: '{{host}}'
  tasks:
    - name: Create a network
      docker_network:
        name: example_app
    - name: Re-create example-app container
      docker_container:
        name: example-app
        image: 'atabbakh/example-app:{{tag}}'
        state: present
        ports:
          - "80:8000"
        networks:
          - name: example_app
        recreate: yes
    - name: Restart a container
      docker_container:
        name: example-app
        image: 'atabbakh/example-app:{{tag}}'
        state: started
        restart: yes